[tools]
python = "3.13.5"

[tasks.setup]
description = "Setup project"
run = [
    "mise i",
    "pip3 install --quiet --upgrade pip",
    "pip3 install --quiet online-judge-tools online-judge-verify-helper setuptools",
    "which xclip > /dev/null || (sudo apt update -qq && sudo apt install -qq xclip)",
    "which g++-12 > /dev/null || (sudo apt update -qq && sudo apt install -qq g++-12)",
]
