[[languages.cpp.environments]]
CXX = "g++"
CXXFLAGS = [
    "-O2",
    "-Wall",
    "-Wextra",
    "-fconstexpr-depth=1024",
    "-fconstexpr-loop-limit=524288",
    "-fconstexpr-ops-limit=2097152",
    "-flto=auto",
    "-march=native",
    "--std=gnu++23",
    "-I./lib",
]
